# Generated by Django 6.0.3 on 2026-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_internshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='logbook',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='supervisor_comment',
            field=models.TextField(blank=True),
        ),
    ]
