# Generated by Django 6.0.3 on 2026-03-05 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_logbook_review_status_logbook_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_internships', to=settings.AUTH_USER_MODEL),
        ),
    ]
