# Generated by Django 6.0.3 on 2026-03-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_internship_assigned_at_internship_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='company_confirmation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanyCoordinatorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_messages', to='ims.company')),
                ('coordinator', models.ForeignKey(limit_choices_to={'role': 'coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_company_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='ims.company')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_representative_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
