# Generated by Django 6.0.3 on 2026-03-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_internship_company_confirmation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
