# Generated by Django 6.0.3 on 2026-03-22 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_student_address_student_date_of_birth_student_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='internship',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='internship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='internship',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='internship',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='internship',
            name='work_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='ims.student'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_internships', to=settings.AUTH_USER_MODEL),
        ),
    ]
