# Generated by Django 6.0.3 on 2026-03-22 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_internship_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ims.internship'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12),
        ),
    ]
